var elaborantApp = angular.module('elaborant', ["elaborantRouter",
												"elaborantChart",
												"angularMoment", 
												"btorfs.multiselect", 
												"ui.bootstrap",
												
												"elaborantLaboratoryCtrl",
												"elaborantLaboratoryManagerCtrl",
												"elaborantLaboratoryService",
												"elaborantComputerCtrl",
												"elaborantComputerManagerCtrl",
												"elaborantComputerService",
												"elaborantLoginCtrl",
												"elaborantLoginService",
												"elaborantUserCtrl",
												"elaborantUserManagerCtrl",
												"elaborantProblemCtrl",
												"elaborantProblemManagerCtrl",
												"elaborantTaskCtrl",
												"elaborantTaskManagerCtrl",
												"elaborantLoginService",
												"elaborantTaskService",
												"elaborantUserService",
												"elaborantModalService",
												"elaborantNotificationService"
												]);