var elaborantApp = angular.module('elaborant', ["elaborantRouter",
												"angularMoment", 
												"btorfs.multiselect", 
												"ui.bootstrap",
												"elaborantLaboratoryCtrl",
												"elaborantComputerCtrl",
												"elaborantLoginCtrl",
												"elaborantLoginService",
												"elaborantUserCtrl",
												"elaborantProblemCtrl",
												"elaborantTaskCtrl",
												"elaborantTaskManagerCtrl",
												"elaborantLoginService",
												"elaborantTaskService"
												]);